import { Sofia_Sans, Playfair_Display } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'

const sofia = Sofia_Sans({ subsets: ['latin'] })
const playfair = Playfair_Display({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`w-full  flex justify-center items-center flex-col ${playfair.className}`}
      >
        <NavBar />
        <main className="w-[1440px]">{children}</main>
      </body>
    </html>
  )
}
