import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`w-full  flex justify-center items-center flex-col ${inter.className}`}
      >
        <NavBar />
        <main className="w-[1440px]">{children}</main>
      </body>
    </html>
  )
}
